### ISSUE TITLE
GL versions less than 2.0 generate GLES bindings instead

### ISSUE THREAD

**Issue by tgschultz** [castholm/zigglgen#3]
This seems to have been intentional based on: [these lines](https://github.com/castholm/zigglgen/blob/dc6fa357bbc75cb18dd47a7ef778d7874c706c49/zigglgen/generator.zig#L93-L96):
```zig
        // Fix up API
        if (version[0] < 2) {
            api = .gles1;
        }
```
But I can't figure out why. This prevents the creation of working non-ES OpenGL 1.x bindings, rare as it may be that anyone should need such a thing. I would submit a patch that only applies this "fix" in the case that the API was already gles, but I'm reluctant to without knowing the reason it exists in the first place.

**Comment by castholm** [comment]
Thanks for reporting and submitting a patch for this, I'll publish a new release in a few minutes after I've tested everything.

For posterity, the reason for this fixup is that the XML API registry encodes GLES as two separate APIs, `gles1` for ES 1.0/1.1 and `gles2` for 2.0 and beyond. I think that's confusing and that it makes more sense to group them all under the same `gles` label for simplicity, so that's what I did with the public API, converting it back to the split API internally. I just forgot to also check that the chosen API was ES.
